apiVersion: v1 
kind: Pod
metadata: 
  name: pod-3
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: cont-3
    image: nginx 
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

