apiVersion: v1 
kind: Pod 
metadata:   
  name: pod-affinity 
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            value:
            - gpu
  containers:
  - name: cont-1 
    image: nginx 
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"   


