apiVersion: v1 
kind: Pod
metadata: 
  name: pod-anti-affinity 
spec: 
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: NotIn
            values:
            - gpu
  containers: 
  - name: cont-1 
    image: nginx 
